<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
    <Authors>crygup</Authors>
    <Description>Adds a button to the logbook to mark an entire section as read.</Description>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GameDir Condition="'$(GameDir)' == ''">C:/Program Files (x86)/Steam/steamapps/common/Risk of Rain 2</GameDir>
    <ProfileDir Condition="'$(ProfileDir)' == ''">$(APPDATA)/r2modmanPlus-local/RiskOfRain2/profiles/Default</ProfileDir>
    <Managed>$(GameDir)/Risk of Rain 2_Data/Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Plugin.cs;PageRead.cs" />
    <Reference Include="$(Managed)/RoR2.dll;$(Managed)/UnityEngine.dll;$(Managed)/UnityEngine.CoreModule.dll;$(Managed)/UnityEngine.UI.dll;$(Managed)/UnityEngine.UIModule.dll;$(Managed)/Unity.TextMeshPro.dll;$(ProfileDir)/BepInEx/core/BepInEx.dll;$(ProfileDir)/BepInEx/core/0Harmony.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

